config/routes.rb
Rails.application.routes.draw do

  root 'home#welcome'

  namespace :home do
    get :welcome
    get :index
  end

  namespace :authentication do
    get :authorize_user
    get :logout_user
  end

  resources :destinations, only: [] do
    collection do
      post :update
      get :list
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authorize_token
    session[:user_hash] ||= nil

    if session[:user_hash].blank?
      redirect_to root_path
    end
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def authorize_user
    connection = FaradayBuilder.travel_api_authorize(
      'https://young-beyond-8772.herokuapp.com/auth',
      params[:name]
    )
    session[:user_hash] = connection.post.body

    redirect_to home_index_path
  end

  def logout_user
    session.delete(:user_hash)
    session.delete(:destination_list)

    redirect_to root_path
  end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

  before_action :authorize_token, only: [:update]

  def update

    connection = FaradayBuilder.travel_api_update_destinations(
      "https://young-beyond-8772.herokuapp.com/travelers/#{session[:user_hash]["id"]}",
      session[:user_hash]["token"],
      JSON.parse(params[:destinations])
    )
    response = connection.patch.body

    respond_to do |format|
      format.json { render json: { status: :ok, destinations: response["destinations"] }}
    end
  end

  def list
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authorize_token, only: [:index]

  def welcome
  end

  def index
    if session[:destination_list].blank?
      connection = FaradayBuilder.travel_api_client(
        'https://young-beyond-8772.herokuapp.com/travelers.json',
        session[:user_hash]["token"]
      )
      session[:destination_list] = connection.get.body
    end

    @amos_destinations = session[:destination_list][0]["destinations"]
    @andy_destinations = session[:destination_list][1]["destinations"]
    @evie_destinations = session[:destination_list][2]["destinations"]

    @is_disable = {}
    @is_disable[:amos] = (session[:user_hash]["name"] != "amos")
    @is_disable[:andy] = (session[:user_hash]["name"] != "andy")
    @is_disable[:evie] = (session[:user_hash]["name"] != "evie")

    @destinations = Country.all.map { |c| c.first }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/views/home/_destination.html.slim
tr.destination
  td
    .checkbox
      label
        = check_box_tag nil, name, visited, { disabled: disabled }
        = name if name.present?
  td
    = link_to fa_icon("times"), "javascript:void(0)", data: { name: "#{name}" }, class: 'delete-destination-button'

app/views/home/index.html.slim
#accordion.panel-group role="tablist" aria-multiselectable="true"
  .panel.panel-default
    #headingOne.panel-heading[role="tab"]
      h4.panel-title
        a data-toggle="collapse" data-parent="#accordion" href="#amos-destinations" aria-expanded="true" aria-controls="amos-destinations"
          |  AMOS
    #amos-destinations.panel-collapse.collapse role="tabpanel" aria-labelledby="headingOne"
      .panel-body
        .table-responsive
          table.table.table-hover
            - @amos_destinations.each do |destination|
              = render "destination", name: destination["name"], visited: destination["visited"], disabled: @is_disable[:amos]
  .panel.panel-default
    #headingTwo.panel-heading role="tab"
      h4.panel-title
        a.collapsed data-toggle="collapse" data-parent="#accordion" href="#andy-destinations" aria-expanded="false" aria-controls="andy-destinations"
          |  ANDY
    #andy-destinations.panel-collapse.collapse role="tabpanel" aria-labelledby="headingTwo"
      .panel-body
        .table-responsive
          table.table.table-hover
            - @andy_destinations.each do |destination|
              = render "destination", name: destination["name"], visited: destination["visited"], disabled: @is_disable[:andy]
  .panel.panel-default
    #headingThree.panel-heading role="tab"
      h4.panel-title
        a.collapsed data-toggle="collapse" data-parent="#accordion" href="#evie-destinations" aria-expanded="false" aria-controls="evie-destinations"
          |  EVIE
    #evie-destinations.panel-collapse.collapse role="tabpanel" aria-labelledby="headingThree"
      .panel-body
        .table-responsive
          table.table.table-hover
            - @evie_destinations.each do |destination|
              = render "destination", name: destination["name"], visited: destination["visited"], disabled: @is_disable[:evie]

.new-destination
  = label_tag("New destination")
  = select_tag(:name, options_for_select([""] + @destinations), {class: 'form-control form-select2', placeholder: 'Enter a location'})
  = link_to "Add new destination", nil, class: 'btn btn-primary', id: "add-destination-button"

javascript:
  $(function(){
    // run select2
    $(".form-select2").select2({allowClear: true});

    // automatically load destinations of current user
    var currentUserDestinations = "##{session[:user_hash]["name"]}" + "-destinations";
    $(currentUserDestinations).addClass("in");

    // only bind click events of currentUserDestinations
    var userHash = {};
    userHash["token"] = "#{session[:user_hash]["token"]}";
    userHash["id"] = "#{session[:user_hash]["id"]}";

    actionsHandler(currentUserDestinations, userHash, "full");
  })

app/views/home/welcome.html.slim
= form_tag authentication_authorize_user_path, { method: :get }
  .form-group
    = label_tag("Traveler's Name", nil)
    = text_field_tag(:name, nil, class: 'form-control', placeholder: 'Amos, Andy or Evie')

  = submit_tag("Enter", class: 'btn btn-primary full-width')

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Travelers
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = render '/shared/header'

    .container-fluid
      .row
        .col-sm-12
          = yield

app/views/shared/_header.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      - if session[:user_hash].present?
        button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
          span.sr-only
            | Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
      a.navbar-brand href="#{session[:user_hash].present? ? home_index_path : root_path}"
        | Travel Notes
    - if session[:user_hash].present?
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav.navbar-right
          li
            a href="javascript:void(0)"
              = "Hello #{session[:user_hash]["name"].titleize}"
          li
            = link_to "Leave", authentication_logout_user_path